## [A Neural Network in 11 lines of Python (Part 1)](http://iamtrask.github.io/2015/07/12/basic-python-network/)
A bare bones neural network implementation to describe the inner workings of backpropagation.
Posted by iamtrask on July 12, 2015

In [2]:
import numpy as np

print(f"training ...")

In [4]:
X = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
y = np.array([[0,1,1,0]]).T
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1
for j in range(60000):
    l1 = 1/(1+np.exp(-(np.dot(X,syn0))))
    l2 = 1/(1+np.exp(-(np.dot(l1,syn1))))
    l2_delta = (y - l2)*(l2*(1-l2))
    l1_delta = l2_delta.dot(syn1.T) * (l1 * (1-l1))
    syn1 += l1.T.dot(l2_delta)
    syn0 += X.T.dot(l1_delta)

In [5]:
print(f"testing ...")
l1 = 1/(1+np.exp(-(np.dot(X,syn0))))
l2 = 1/(1+np.exp(-(np.dot(l1,syn1))))
print(f"X: {X}")
print(f"y: {y}")
print(f"Net(X): {l2}")



testing ...
X: [[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
y: [[0]
 [1]
 [1]
 [0]]
Net(X): [[0.00202864]
 [0.99579643]
 [0.99671764]
 [0.00505434]]
